apiVersion: 2019-12-01
location: northeurope
name: SQLAppGroup
properties:
  containers: 
  - name: db
    properties:
      image: appregistry3100.azurecr.io/mysql-custom-image:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 3306
  - name: web
    properties:
      image: appregistry3100.azurecr.io/sqlapp:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 80          
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 80
  imageRegistryCredentials:
    - server: appregistry3100.azurecr.io
      username: appregistry3100
      password: mg4KoqtEMkhx15SUnsDqFIynJANMtbk4ac/QeJy+s4+ACRCKBG+q
type: Microsoft.ContainerInstance/containerGroups