apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: sqlapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlapp
spec:
  selector:
    matchLabels:
      app: sqlapp
  template:
    metadata:
      labels:
        app: sqlapp
    spec:
      containers:
      - image: appregistry3100.azurecr.io/sqlapp:latest
        name: sqlapp
        ports:
        - containerPort: 80
          name: sqlapp